# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "commutative-diagrams-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
hashconsing = "1.5.1"
serde = { version = "1.0.147", features = [ "derive" ] }
